### ISSUE TITLE
Upcoming HTTP deprecation

### ISSUE THREAD

**Issue by quinnj** [randyzwitch/OAuth.jl#17]
a new tag of HTTP will be released soon that deprecates `HTTP.escape` for `HTTP.escapeuri`. There will be a proper deprecation, but this is just a heads up.

**Comment by randyzwitch** [comment]
Thanks for letting me know

**Comment by randyzwitch** [comment]
Fixed by https://github.com/randyzwitch/OAuth.jl/commit/9c52a254f48502841159657b9f74bd22fd583880
