### ISSUE TITLE
Nonce generation uses insecure random

### ISSUE THREAD

**Issue by chethega** [randyzwitch/OAuth.jl#24]
Consider this [line](https://github.com/randyzwitch/OAuth.jl/blob/2991f02d4f584196d872c642636c33108a1ea047/src/OAuth.jl#L49).

This generates a nonce using the default random, which is Mersenne Twister. MT is not a CSPRNG, i.e. the internal state and hence all past and future random numbers can be extracted from a few random numbers from the stream.

The nonce generation should use a secure random instead. For example, `const CSPRNG = Random.RandomDevice()` and `randstring(CSPRNG, length)` would do the job.

Cf general discussion (here)[https://github.com/JuliaLang/julia/issues/32954].

**Comment by randyzwitch** [comment]
If this is important to you, I'm happy to accept a PR

**Comment by chethega** [comment]
It's not important to me personally, since I don't use OAuth.jl. But it does impact the security of all your users against replay attacks.

I'll ping you when julialang has settled on an official recommendation. I am guessing that the amount of affected users and the number of real-world attackers are small enough that this can wait until then, but you are in a better position to judge that.
