### ISSUE TITLE
Can I use OAuth.jl to configure a callback URL to your server?

### ISSUE THREAD

**Issue by logankilpatrick** [randyzwitch/OAuth.jl#25]
Hey! I am trying to set up a program that pings an API. However, the API uses OAuth 2.0 so I need to set up a "configure a callback URL to your server". Is it possible to do this with OAuth.jl and if so, can you provide a simple example and what my URL would me?

Ported over from: https://github.com/JuliaWeb/HTTP.jl/issues/485

**Comment by randyzwitch** [comment]
As I wrote in the other issue, OAuth 1 and OAuth 2 are completely different, though they share a similar name. This package only does the cryptographic signing bits of OAuth 1.0, it doesn't implement anything having to do with actually making requests. You can think of this package as just a way to put a signature on your requests, you can't actually send them without HTTP.jl (where you came from)
