### ISSUE TITLE
Removing `encodeURI`

### ISSUE THREAD

**Issue by IainNZ** [randyzwitch/OAuth.jl#3]
Hey @randyzwitch,

As part of efforts to rationalize and simplify JuliaWeb, I'm removing the `encodeURI` method of HttpCommon.jl. 
https://github.com/JuliaWeb/HttpCommon.jl/pull/29
As far as I can tell, this package is the only one using it, so I wanted to notify you personally. `JuliaWeb/URIParser.jl` has a `URIParser.escape` method that does the same thing, and I'm more confident in that code as well (Keno wrote it, and its better tested). I'd guess the simplest change would be to define your own one-line alias for the URIParser version.

**Comment by randyzwitch** [comment]
Not sure what the bigger honor is: getting a personalized note from @IainNZ or that @jbn decided to fix it while I was chasing my kids around

**Comment by jbn** [comment]
Hah. Definitely the @IainNZ note. 

I've been using `OAuth.jl` for a side project. For a minute early in the day, I thought I somehow introduced a regression on the last PR I submitted. Panic provoked the fresh one! Although, I'm glad you got to chase your kids today, rather than fix #3.

**Comment by randyzwitch** [comment]
Cool, `OAuth.jl` is working for you? I shouldn't be surprised, but since I haven't gotten any feedback other than `Twitter.jl` works (also my package), it's great to get outside validation.

What API are you accessing? @quinnj made a [Yelp API](https://github.com/quinnj/Yelp.jl) wrapper, but I never got around to re-factoring his code to use `OAuth.jl`

**Comment by jbn** [comment]
@randyzwitch Yes. It's working great, thanks! 

I vaguely remember having a concern with something related to stringifying. I'm not near my development box right now though. I just stuck a shiv in my code with the intention of perusing yours in the future. And, while doing that, I'll probably help fill out the test todos. (Writing tests seems to be such a great way to learn a library. How fortunate!)

I started using `OAuth.jl` on a private (non-disclosable) API. Worked perfectly. And, I've been toying at an experimental Twitter API. I'll give you a peek soon by way of a private repo temporary add if you want.

**Comment by IainNZ** [comment]
:+1:
