### ISSUE TITLE
Tests fail on 0.3 on PkgEval

### ISSUE THREAD

**Issue by IainNZ** [randyzwitch/OAuth.jl#9]
http://pkg.julialang.org/logs/OAuth_0.3.log

**Comment by randyzwitch** [comment]
Well, yeah. REQUIRES shows julia 0.4-

**Comment by IainNZ** [comment]
Tests in the last version for 0.3, `v0.2.0` - check the log. PkgEval is just Pkg.add and Pkg.test with the results stored.

**Comment by randyzwitch** [comment]
Right, the log says:

```
INFO: METADATA is out-of-date — you may not have the latest version of OAuth
INFO: Use `Pkg.update()` to get the latest versions of your packages
```

5 days ago `v0.3.0` was merged to METADATA.

**Comment by IainNZ** [comment]
PkgEval does tests on Julia 0.3 and 0.4. On Julia 0.4, it gets OAuth 0.3.0 (http://pkg.julialang.org/logs/OAuth_0.4.log), and on Julia 0.3, it gets OAuth 0.2.0, just like a real user. 

The tests take hours to run, so by `O` METADATA is getting slightly out of date.
